version: '3.3'

networks:
  default:
    external:
      name: network_default

volumes:
  mautic-web:
  mautic-db:

services:

  mautic:
    container_name: llt.mautic
    hostname: ${DOMAIN}
    restart: unless-stopped
    image: mautic/mautic:v3
    expose:
    - 80
    - 443
    environment:
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_HOST_NAME: "mautic"
      MAUTIC_DB_HOST: mautic_db
      MAUTIC_DB_USER: ${USER_NAME}
      MAUTIC_DB_PASSWORD: ${USER_PASSWORD}
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
      MAUTIC_RUN_CRON_JOBS: "true"
    volumes:
    - mautic-web:/var/www/html
    depends_on: 
    - mautic_db

  mautic_db:
    container_name: llt.mautic.db
    image: powertic/percona-docker
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASSWORD}
    ports:
    - 3306:3306
    volumes:
    - mautic-db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""

  mautic_db_admin:
    container_name: llt.mautic.db.admin
    image: phpmyadmin/phpmyadmin
    environment:
      VIRTUAL_HOST: pma.${DOMAIN}
      LETSENCRYPT_HOST: pma.${DOMAIN}
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
      PMA_ARBITRARY: 1
    restart: unless-stopped
    volumes:
    - /sessions
    depends_on: 
      - mautic_db