version: '3.6'

networks:
  default:
    external:
      name: network_default

volumes:
  mautic-web:

services:
  mautic:
    container_name: ltt.mautic
    hostname: mautic.${DOMAIN}
    restart: unless-stopped
    image: mautic/mautic
    expose:
    - 80
    - 443
    environment:
      LETSENCRYPT_HOST: mautic.${DOMAIN}
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
      VIRTUAL_HOST: mautic.${DOMAIN}
      VIRTUAL_HOST_NAME: "mautic"
      MAUTIC_DB_HOST: mariadb
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: ${USER_PASSWORD}
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
      MAUTIC_RUN_CRON_JOBS: "true"
    volumes:
    - mautic-web:/var/www/html
